### ISSUE TITLE
link to specification shown on the RAW BLE broadcast page is broken

### ISSUE THREAD

**Issue by ekuleshov** [NordicSemiconductor/Android-nRF-Connect#153] opened 2021-07-08 12:55 UTC
**Describe the bug**

The link to BLE specification shown on the RAW BLE broadcast page is giving 404 error
https://www.bluetooth.com/en-us/specifications/assigned-numbers/generic-access-profile

**To Reproduce**
1. Scan for devices
2. Tap on RAW button in any of them
3. Then tap on the link at the bottom of the dialog

**Expected behavior**
Full link to the corresponding document is
https://btprodspecificationrefs.blob.core.windows.net/assigned-numbers/Assigned%20Number%20Types/Generic%20Access%20Profile.pdf

Or at the parent page
https://www.bluetooth.com/specifications/assigned-numbers/#:~:text=Generic%20Access%20Profile

**Screenshots**
n/a

**Versions (please complete the following information):**
 - Android version: n/a
 - Phone model n/a
 - App Version - latest from the app store

**Additional context**
n/a

**Comment by philips77** [comment] 2021-07-10 04:52
Duplicate of #148

**Closed by philips77** 2021-07-10 04:52 UTC
Labels: bug
