### ISSUE TITLE
Auto-select text input when CPF descriptor with UTF-8 is present

### ISSUE THREAD

**Issue by carlescufi** [NordicSemiconductor/Android-nRF-Connect#82] opened 2018-09-18 16:01 UTC
When a Characteristic contains a Characteristic Presentation Format that contains UTF-8 as its value, nRF Connect Should switch to text input instead of hex, since the contents of the characteristic value are supposed to be UTF-8 encoded text.

CC @mostafaberg @jovirus @roshanrajaratnam @philips77

CC @jhedberg

**Comment by philips77** [comment] 2018-09-18 16:26
Easy. Had you written this 1h earlier, you'd have had it in the released that just went public :)

**Comment by philips77** [comment] 2018-09-18 16:39
The problem is with other values of this descriptor. Why utf8 will have a string input while other values a generic one. But I understand your use case. Let's say this is the most common.

**Comment by philips77** [comment] 2018-09-19 15:20
Released in version 4.20.2.

**Closed by philips77** 2018-09-19 15:20 UTC
Labels: enhancement
