### ISSUE TITLE
Is there a source code for Android apps?

### ISSUE THREAD

**Issue by hjh2881** [NordicSemiconductor/Android-nRF-Connect#128] opened 2020-05-29 07:36 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by philips77** [comment] 2020-05-29 07:49
No, the app is not open sourced.
It's written on Readme: https://github.com/NordicSemiconductor/Android-nRF-Connect#application
Duplicate of #1, #49, #53, #96, #103.

**Closed by philips77** 2020-05-29 07:49 UTC

**Comment by philips77** [comment] 2020-05-29 07:50
We have open sourced our other [Android](https://github.com/NordicSemiconductor?q=android&type=&language=) and [iOS](https://github.com/NordicSemiconductor?q=IOS&type=&language=) apps.

**Comment by hjh2881** [comment] 2020-06-01 02:47
Thank you very much.
